const WIDTH = 500;
const HEIGHT = 500;
const TILE_SIZES = [50,25,20,10,5,4,2,1];
const MAX_GROWTH = 15;
const GROWTH_BASE_PRICE = 10;
const SPEED_BASE_PRICE = 50;
const SIZE_BASE_PRICE = 75;
const TILE_BASE_PRICE = 150;
const TICK_BASE_PRICE = 5;
const GROWTH_RATE_MULTIPLIER = 1.2;
const TICK_BASE_MULTIPLIER = 1.2;
const MOWER_RATE_MULTIPLIER = 2.5;
const MOWER_SIZE_MULTIPLIER = 1.5;
const TILE_SIZE_MULTIPLIER = 3.5;

export {
    WIDTH,
    HEIGHT,
    TILE_SIZES,
    MAX_GROWTH,
    GROWTH_BASE_PRICE,
    SPEED_BASE_PRICE,
    SIZE_BASE_PRICE,
    TILE_BASE_PRICE,
    TICK_BASE_PRICE,
    GROWTH_RATE_MULTIPLIER,
    TICK_BASE_MULTIPLIER,
    MOWER_RATE_MULTIPLIER,
    MOWER_SIZE_MULTIPLIER,
    TILE_SIZE_MULTIPLIER,
}
